FROM floydhub/tensorflow:1.12-py3_aws.40
MAINTAINER Floyd Labs "support@floydhub.com"

RUN \
    pip --no-cache-dir install \
        mxnet==1.2.0 \
        tensorboardX \
    && rm -rf /tmp/* \
    && rm -rf /root/.cache